apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: vllm-test-may26 
  janus-idp.io/tekton: vllm-test-may26
  backstage.io/kubernetes-id: vllm-test-may26
  backstage.io/kubernetes-namespace: rhdh-app 
  app.kubernetes.io/part-of: vllm-test-may26
resources: 
- application-dev.yaml