---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    app.kubernetes.io/instance: vllm-test-may26
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: vllm-test-may26 
  name: vllm-test-may26
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi