apiVersion: batch/v1
kind: Job
metadata:
  name: dsp-clone-job-vllm-test-may26-gitops
spec:  
  template:         
    metadata:
      name: dsp-clone-job-vllm-test-may26-gitops
    spec:  
      serviceAccountName: vllm-test-may26-dsp-job
      containers:
      - name: initialize-dsp
        image: quay.io/redhat-ai-dev/utils:latest
        command:
        - /bin/bash
        - -c
        - |
          NS=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)
          oc wait -l statefulset=vllm-test-may26-notebook --for=condition=ready pod --timeout=300s
          oc exec  StatefulSet/vllm-test-may26-notebook -- git clone https://github.com/jdubrick-ai/vllm-test-may26
      restartPolicy: Never